name = "snapsight2"
compatibility_date = "2024-09-28"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "SNAPSIGHT_BUCKET"
bucket_name = "snapsight"

[observability]
enabled = true
head_sampling_rate = 1